config/routes.rb
Rails.application.routes.draw do
  resources :watch_histories,   only: [:index, :update]
  resources :favorites,         only: [:create, :destroy]
  resources :people,            only: [:edit, :update]
  resources :video_comments,    only: [:create, :update, :destroy]
  resources :profile_comments,  only: [:create, :update, :destroy]
  resources :movie_ratings,     only: [:create, :update, :destroy]
  resources :movie_actors,      only: [:create, :update, :destroy]
  resources :movie_genres,      only: [:create, :update, :destroy]
  resources :movies,            except: [:index]
  resources :episodes,          except: [:index, :show]
  resources :videos,            only: [:show]
  resources :show_actors,       only: [:create, :update, :destroy]
  resources :show_ratings,      only: [:create, :update, :destroy]
  resources :show_genres,       only: [:create, :update, :destroy]
  resources :shows,             except: [:index]
  resources :subscriptions,     only: [:create, :update]
  resources :customers,         except: [:index, :edit, :update]
  resources :producers,         except: [:index, :edit, :update]
  resources :friend_requests,   only: [:create, :update, :destroy]
  resources :account_activations, only: [:edit]
  root    'static_pages#home'
  get     '/about',   to: 'static_pages#about'
  get     '/contact', to: 'static_pages#contact'
  get     '/browse',  to: 'static_pages#browse'
  get     '/signup',  to: 'customers#new'
  get     '/psignup', to: 'producers#new'
  get     '/search',  to: 'static_pages#search', :as => 'search_page'
  get     '/myshows', to: 'static_pages#shows',  :as => 'my_shows'
  get     '/pro_shows', to: 'static_pages#_pro_shows'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  get     '/friends', to: 'static_pages#friends'
  delete  '/friends/:id', to: 'friends#destroy'
  get     '/my_rentals',  to: 'static_pages#my_rentals'
  post    '/movies/:id/rent', to: 'rentals#create'
  get     '/invoice', to: 'static_pages#invoice'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  #Authorization
  before_action :logged_in_customer, only: [:shows, :search, :friends, :friend_search]
  
  def home
    # Try to get videos to display on customer homepage
    if logged_in? and current_person.customer?
      # Try to get most recent video
      if current_person.user.watch_histories.any?
        # Get last watched video history
        recent_watch = current_person.user.watch_histories.order(updated_at: :desc).first
        # Generate suggestions based on last video watched
        s_genre = recent_watch.video.get_content_genres.first
        if s_genre.nil?
          # Last video doesn't have genre set, get 6 random shows
          @suggestions = random_shows
        else
          # Get 6 recently updated shows with same genre
          @suggestions = Show.with_attached_promo_image.order(updated_at: :desc).joins(:show_genres).where( show_genres: { genre: s_genre.genre } ).limit(6)
        end
        
        # Jumbotron video
        # 1. Continue watching
        if !recent_watch.completed
          @video = recent_watch.video
          @video_progress = recent_watch.progress
        else
          # 2. Next episode if available
          # might want to change to be episode.get(sub.current_ep).video if show.episodes >= sub.current_ep
          next_ep = recent_watch.video.next_video
          if !next_ep.nil?
            @video = next_ep
          else
            # 3. Next episode from random sub
            current_person.user.subscriptions.includes(:show).each do |sub|
              if sub.show.episodes.size > sub.current_episode
                @video = sub.show.episodes.find_by(absolute_episode: sub.current_episode+1).video
                break
              end
            end
          end
        end
        # 4. Nothing, link to browse page
      else
        # Customer not watched anything, random suggestions
        @suggestions = random_shows
      end
    end
  end

  def about
  end

  def contact
  end
  
  def search
    if !params[:search].blank?  
      parameter = params[:search].downcase
      show_results = Show.includes(:show_genres).where("lower(Shows.name) LIKE :search", search: "%#{parameter}%")
      movie_results = Movie.joins(:video).includes(:movie_genres).where("lower(videos.title) LIKE :search", search: "%#{parameter}%")
      
      # Filter search results
      if params[:filters]
        unless params[:filters][:genre].empty?
          # Convert "Genre title" into "genre_title"
          genre_param = params[:filters][:genre].parameterize.underscore
          # Genre filter
          show_results = show_results.joins(:show_genres).where(show_genres: { genre: genre_param } )
          movie_results = movie_results.joins(:movie_genres).where(movie_genres: { genre: genre_param } )
        end
        unless params[:filters][:actor].empty?
          # Actor search, case insensitive
          show_results = show_results.joins(:show_actors).where("lower(show_actors.name) LIKE ?", "%#{params[:filters][:actor]}%")
          movie_results = movie_results.joins(:movie_actors).where("lower(movie_actors.name) LIKE ?", "%#{params[:filters][:actor]}%")
        end
      end
      
      # Combine results
      @results = show_results + movie_results
    elsif !params[:fsearch].blank?
      friend_search
    else
      redirect_to(browse_path)
    end
  end
  
  def shows
  end
  
  def friends
    @friends = current_person.user.friends.includes(person: {avatar_attachment: :blob})
    @requests = current_person.user.friend_requests.includes(requester: { person: {avatar_attachment: :blob}})
  end
  
  def friend_search
    @parameter = params[:fsearch].downcase
    @results = Customer.joins(:person).search("%#{@parameter}%")
  end
  
  private
    def random_shows(num = 6)
      Show.with_attached_promo_image.offset(rand(Show.count - num + 1)).limit(num)
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_home_customer.html.erb
<% provide(:title, "Home") %>
<div class="container" id="customer-home">
  <%= render "flash_notice" %>
  <div class="row">
    <div class="col">
      <% if !@video.nil? %>
        <div class="jumbotron" style="background-image: url('<%= url_for @video.content_parent.promo_image %>')">
          <h2 class="display-4"><%= @video.content_parent.title %></h2>
          <% if @video.episode? %>
            <h5><%= @video.title %> <small><%= @video.content.season_episode %></small></h5>
          <% end %>
          <%= link_to @video_progress.nil? ? "Watch Next" : "Continue Watching", @video, class: "btn btn-dark" %>
        </div>
      <% else %>
        <div class="jumbotron" style="background-image: url('<%= url_for Show.last.promo_image %>')">
          <h2 class="display-4">Find something to watch!</h2>
          <%= link_to "Browse content", browse_path, class: "btn btn-dark" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row" id="home-subscriptions">
    <div class="col">
      <div class="home-header"><h3>Your Subscriptions</h3></div>
      <div class="scrolling-wrapper">
        <% if current_person.user.subscriptions.any? %>
          <% current_person.user.subscriptions.includes(show: {promo_image_attachment: :blob}).each do |sub| %>
            <%= link_to sub.show do %>
              <div class="card">
                <%= image_tag url_for(sub.show.promo_image), class: "card-img-top" if sub.show.promo_image.attached? %>
                <h5 id="card-text" class="card-header"><%= truncate sub.show.name, length: 16 %></h5>
              </div>
            <% end %>
          <% end %>
        <% end %>
        <%= link_to browse_path do %>
          <div class="card">
            <%= image_tag "homepage/04.jpg", class: "card-img-top" %>
            <h5 id="card-text" class="card-header">Find some shows!</h5>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <hr>
  <div class="row" id="home-recommendations">
    <div class="col">
      <div class="home-header"><h3>Your Recommendations</h3></div>
      <div class="scrolling-wrapper">
        <% @suggestions.each do |show| %>
          <%= link_to show do %>
            <div class="card">
              <%= image_tag url_for(show.promo_image), class: "card-img-top" if show.promo_image.attached? %>
              <h5 id="card-text" class="card-header"><%= truncate show.name, length: 16 %></h5>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <hr>
  <div class="row" id="home-recent">
    <div class="col">
      <div class="home-header"><h3>Recently Updated</h3></div>
      <div class="scrolling-wrapper">
        <% Show.with_attached_promo_image.order(updated_at: :desc).limit(10).each do |show| %>
          <%= link_to show do %>
            <div class="card">
              <%= image_tag url_for(show.promo_image), class: "card-img-top" if show.promo_image.attached? %>
              <h5 id="card-text" class="card-header"><%= truncate show.name, length: 16 %></h5>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_home_guest.html.erb
<div class="container-fluid">
  <div class="guest-fill row justify-content-center align-items-center">
    <div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
      <div class="carousel-inner">
        <% (1..4).each do |num| %>
        <div class="item<%= " active" if num == 1 %>">
          <%= image_tag "homepage/0#{num}.jpg", alt: "Slide #{num}" %>
          <div class="carousel-caption">
            <h2 class="text-main">
              Say hello to subscriptions.
            </h2>
            <h4>
              Pick your shows, sit back, and enjoy.
            </h4>
            <h2>
              <%= link_to "Sign up today", signup_path, class: "btn btn-primary btn-large" %>
              <%= link_to "Producer? Sign up here", psignup_path, class: "btn btn-primary btn-lg" %>
            </h2>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_pro_shows.html.erb
<div class="container">
  <%= render "flash_notice" %>
  <div class="row">
    <div class="col">
      <h3>My Shows</h3>
      <hr>
      <% current_person.user.shows.each do |theshow| %>
        <div class="row subscription">
          <div class="col-sm-2">
            <% if theshow.promo_image.attached? %>
              <%= image_tag(url_for(theshow.promo_image), :alt => "Promo Image", :style => "height: 100px; width: 100px;") %>
            <% else %>
              <%= image_tag("nullPhoto.png", :alt => "sub thumbnail", :style => "height: 100px; width: 100px;") %>
            <% end %>
          </div>
          <div class="col-sm-8">
            <b><%= theshow.name %></b>
            <p><%= theshow.description %></p>
          </div>
          <div class="col-sm-2">
            <%= link_to "View Show", theshow, class: "btn btn-primary btn-block btn-sm" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <h3>My Movies</h3>
        <hr>
        <% current_person.user.movies.each do |themovie| %>
          <div class="row subscription">
            <div class="col-sm-2">
              <% if themovie.promo_image.attached? %>
                <%= image_tag(url_for(themovie.promo_image), :alt => "Promo Image", :style => "height: 100px; width: 100px;") %>
              <% else %>
                <%= image_tag("nullPhoto.png", :alt => "sub thumbnail", :style => "height: 100px; width: 100px;") %>
              <% end %>
            </div>
            <div class="col-sm-8">
              <b><%= themovie.video.title %></b>
              <p><%= themovie.video.description %></p>
            </div>
            <div class="col-sm-2">
              <%= link_to "View Movie", themovie, class: "btn btn-primary btn-block btn-sm" %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
  <div id="buttons" class="col text-center">
    <%= link_to "Add New Show", new_show_path, class: "btn btn-primary btn-lg" %>
    <%= link_to "Add New Movie", new_movie_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="container">
    <%= render "flash_notice" %>
    <h2>About</h2>
    <br/>
    <br/>
    
    <div class="row">
        <p>
            Vidon is a video streaming site that allows users to subscribe to the content
            they want to watch, not pay for a bunch of content they don't need. Vidon also
            provides basic social media features such as friends, and being able to comment
            on videos and people's profiles. 
        </p>
        <br/>
        <p>
            Vidon is a student developed project created by the members of i/onicSoft 
            for the express purpose of research and academic development. No actual monetary
            transactions are performed, and all content hosted on this website is from the public domain.
        </p>
    </div>
</div>

app/views/static_pages/browse.html.erb
<% provide(:title, "Browse") %>
<div class="container">
  <%= render "flash_notice" %>
  <div class="row">
    <div class="col">
      <nav role="navigation">
        <ul class="nav nav-tabs nav-fill" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="shows-tab" data-toggle="tab" href="#shows" role="tab">Shows</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="browse-tab" data-toggle="tab" href="#movies" role="tab">Movies</a>
          </li>
        </ul>
      </nav>
      <div class="tab-content">
        <div class="tab-pane fade show active" id="shows" role="tabpanel">
          <div class="row pt-2 m-0">
            <% Show.with_attached_promo_image.all.each do |show| %>
              <div class="col-4 showcard p-0">
                <%= link_to show do %>
                  <%= image_tag url_for(show.promo_image) if show.promo_image.attached? %>
                  <div class="shadow"></div>
                  <div class="show-title">
                    <h5><%= show.name %></h5>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="tab-pane fade" id="movies" role="tabpanel">
          <div class="row pt-2 m-0">
            <% Movie.includes(:video).with_attached_promo_image.all.each do |movie| %>
              <div class="col-4 showcard p-0">
                <%= link_to movie do %>
                  <%= image_tag url_for(movie.promo_image) if movie.promo_image.attached? %>
                  <div class="shadow"></div>
                  <div class="show-title">
                    <h5><%= movie.title %></h5>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="container">
    <%= render "flash_notice" %>
    <h2>Contact</h2>
    <br/>
    <br/>
    
    <div class="row">
        <h4>Need Support?</h4>
        <p>
            We at i/onicSoft work hard to make Vidon easy to use, but we know that everyone
            has questions. If you have a question on how something works, or a suggestion
            on how to make things better, contact our support team at the email below:
        </p>
        <br/>
        <br/>
        <h5>ionicsoft@example.com</h5>
    </div>
</div>

app/views/static_pages/friends.html.erb
<% provide(:title, "Friends") %>
<div class="container">
  <%= render "flash_notice" %>
  <div class="row justify-content-center">
    <div class="col-7 pr-0" id="friends-main">
      <div class="card card-default">
        <div class="card-body">
          <h3 id="card-text">Your friends</h3>
          <hr>
          <% @friends.each do |friend| %>
            <div class="media mb-2">
              <%= link_to friend do %>
                <%= image_tag(get_avatar(friend.person), :alt => "Avatar",
                  size: "70x70", class: "mr-3 avatar-img") %>
                <div class="media-body">
                  <%= content_tag :h4, friend.person.full_name, class: "mt-0 text-body" %>
                  <%= link_to "Remove", "#{friends_path}/#{friend.id}",
                    method: :delete, class: "btn btn-warning btn-sm pull-right" %>
                </div>
              <% end %>
            </div>
          <% end %>
          <% if @friends.none? %>
              <p>No friends yet.</p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-5">
      <div id="psearch">
        <%= form_tag(search_page_path, :method => "get", class: 'navbar-form') do %>  
          <div class="input-group">
          <%= search_field_tag :fsearch, params[:fsearch], placeholder: "Search for friends", class: "form-control" %>  
          	<div class="input-group-btn">
              <%= button_tag fa_icon("search"), class: "btn btn-info", id: "friend_search" %>  
          	</div>
        		</div>
        <% end %>
      </div>
      <div class="card card-default mt-3">
        <div class="card-body">
          <h3 id="card-text">Friend Requests</h3>
          <hr>
          <% @requests.each do |frequest| %>
            <div class="media mb-2">
              <% requester = frequest.requester %>
              <%= image_tag(get_avatar(requester.person), :alt => "Avatar",
                size: "70x70", class: "mr-3 avatar-img") %>
              <div class="media-body">
                <%= link_to (content_tag :h4, requester.person.full_name, class: "mt-0 text-body"), requester %>
                <%= form_with(model: frequest) do |form| %>
                  <%= form.submit "Accept", class: "btn btn-info btn-sm" %>
                  <%= link_to "Decline", "#{friend_requests_path}/#{frequest.id}", method: :delete, class: "btn btn-warning btn-sm" %>
                <% end %>
              </div>
            </div>
          <% end %>
          <% if @requests.none? %>
            <p>No pending friend requests.</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? and current_person.customer? %>
  <%= render 'home_customer' %>
<% elsif logged_in? and current_person.producer? %>
  <%= render 'pro_shows' %>
<% else %>
  <%= render 'home_guest' %>
<% end %>

app/views/static_pages/invoice.html.erb
<% provide(:title, "Invoice") %>
<div class="container">
  <%= render "flash_notice" %>
  <div class="row justify-content-center">
    <div class="col-12">
      <div class="card card-default">
        <div class="card-body">
          <h3 id="card-text">Your charges</h3>
          <table class="table table-hover">
            <thead>
              <th scope="col">Description</th>
              <th scope="col">Amount</th>
              <th scope="col">Date</th>
            </thead>
            <tbody>
              <% @charges = Invoice.all.where(payment_id: current_person.user.payment.id).order(created_at: :desc) %>
              <% @charges.each do |charge| %>
                <tr scope="row">
                  <td><%= charge.description %></td>
                  <td><%= number_to_currency charge.amount %></td>
                  <td><%= charge.created_at.strftime("%m/%d/%y") %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div></div></div>

app/views/static_pages/my_rentals.html.erb
<% provide(:title, "Rentals") %>
<div class="container">
  <%= render "flash_notice" %>
  <h3 id="banner">My Rentals</h3>
  <hr>
  <% current_person.user.rentals.includes(movie: [{promo_image_attachment: :blob}, :video]).each do |rental| %>
    <div class="row subscription">
      <div class="col-sm-2">
        <% if rental.movie.promo_image.attached? %>
          <%= image_tag(url_for(rental.movie.promo_image), :alt => "Promo Image", :style => "height: 100px; width: 100px;") %>
        <% else %>
          <%= image_tag("nullPhoto.png", :alt => "nullPhoto", :style => "height: 100px; width: 100px;") %>
        <% end %>
      </div>
      <div class="col-sm-8">
        <b><%= rental.movie.title %></b>
        <p><%= rental.movie.description %></p>
      </div>
      <div class="col-sm-2">
        <%= link_to "Play", rental.movie.video, class: "btn btn-primary btn-block btn-sm" %>
      </div>
    </div>
  <% end %>
  <div class="col-sm-12 text-center">
    <%= link_to "Find new movies!", browse_path(params: {movies: true}), class: "btn btn-primary btn-lg" %>
  </div>
</div>

app/views/static_pages/pro_shows.html.erb
<div class="container">
  <h3>My Shows</h3>
  <hr>
  <% current_person.user.shows.each do |theshow| %>
    <div class="row well">
      <div class="col-sm-2">
        <% if theshow.promo_image.attached? %>
          <%= image_tag(url_for(theshow.promo_image), :alt => "Promo Image", :style => "height: 400px; width: 300px;") %>
        <% else %>
          <%= image_tag("nullPhoto.png", :alt => "sub thumbnail", :style => "height: 100px; width: 100px;") %>
        <% end %>
      </div>
      <div class="col-sm-8">
        <b><%= theshow.name %></b>
        <p><%= theshow.description %></p>
      </div>
      <div class="col-sm-2">
        <%= link_to "View Show", theshow, class: "btn btn-primary btn-block btn-sm" %>
      </div>
    </div>
  <% end %>
  <% current_person.user.movies.each do |themovie| %>
    <div class="row well">
      <div class="col-sm-2">
        <% if themovie.promo_image.attached? %>
          <%= image_tag(url_for(themovie.promo_image), :alt => "Promo Image", :style => "height: 100px; width: 100px;") %>
        <% else %>
          <%= image_tag("nullPhoto.png", :alt => "sub thumbnail", :style => "height: 100px; width: 100px;") %>
        <% end %>
      </div>
      <div class="col-sm-8">
        <b><%= themovie.video.title %></b>
        <p><%= themovie.video.description %></p>
      </div>
      <div class="col-sm-2">
        <%= link_to "View Movie", themovie, class: "btn btn-primary btn-block btn-sm" %>
      </div>
    </div>
  <% end %>
  <div class="col-sm-12 text-center">
    <%= link_to "Add New Show", new_show_path, class: "btn btn-primary btn-lg" %>
    <%= link_to "Add New Movie", new_movie_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

app/views/static_pages/search.html.erb
<% provide(:title, pluralize(@results.count, "Search Result")) %>
<div class="container">
  <%= render "flash_notice" %>
  <div class="row justify-content-center">
    <% unless params[:search].nil? %>
    <div class="col-3" id="search-filters">
      <div class="card card-default">
        <h5 class="card-header text-body"><%= fa_icon "filter", text: "Search filters" %></h5>
        <div class="card-body">
          <%= form_with url: search_page_path, method: :get, local: true do |f| %>
            <div class="form-group">
              <%= f.label :search, "Title" %>
              <%= f.text_field :search, value: params[:search], class: "form-control" %>
            </div>
            
            <%= fields_for :filters do |ff| %>
              <div class="form-group">
                <%= ff.label :genre %>
                <%= ff.select :genre, ShowGenre.genres.keys.map { |w| [w.humanize, w] }, {include_blank: ''}, class: "custom-select" %>
              </div>
              <div class="form-group">
                <%= ff.label :actor %>
                <%= ff.text_field :actor, class: "form-control" %>
              </div>
            <% end %>
            <%= f.submit "Apply", class: "btn btn-primary btn-block" %>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
    
    <div class="col-9" id="search-results">
      <div class="card card-default">
        <div class="card-body">
          <h5 class="text-body">
            <% unless params[:search].nil? %>
              <%= "Found #{@results.count} results for \"#{params[:search]}\"" %>
            <% else %>
              <%= "Found #{@results.count} results for \"#{params[:fsearch]}\"" %>
            <% end %>
          </h5>
          <hr>
          <div class="row pt-2 m-0">
            <% @results.each do |result| %>
              <% if result.is_a?(Customer) %>
                <div class="col-4 showcard p-0">
                  <%= link_to result do %>
                    <%= image_tag url_for(get_avatar result.person) %>
                    <div class="shadow"></div>
                    <div class="show-title">
                      <h5><%= result.person.full_name %></h5>
                    </div>
                  <% end %>
                </div>
              <% else %>
                <div class="col-4 showcard p-0">
                  <%= link_to result do %>
                    <%= image_tag url_for(result.promo_image) if result.promo_image.attached? %>
                    <div class="shadow"></div>
                    <div class="show-title">
                      <small><%= result.class.name %></small>
                      <h5><%= result.title %></h5>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/shows.html.erb
<% provide(:title, "Subscriptions") %>
<div class="container">
  <%= render "flash_notice" %>
  <div class="row">
    <div class="col">
      <div class="card card-default">
        <div class="card-body">
          <h3 class="text-body">My Shows</h3>
          <div class="row">
            <% current_person.user.subscriptions.includes(show: {promo_image_attachment: :blob}).each do |sub| %>
              <div class="col-4 subscription">
                <%= link_to sub.show do %>
                <% if sub.show.promo_image.attached? %>
                  <%= image_tag(url_for(sub.show.promo_image), :alt => "Promo Image", :style => "height: 100px; width: 100px;") %>
                <% else %>
                  <%= image_tag("nullPhoto.png", :alt => "Promo Image", :style => "height: 100px; width: 100px;") %>
                <% end %>
                <p>
                  <b><%= sub.show.name %></b> <%= content_tag :small, "This subscription will not renew", class: "text-secondary" if sub.cancel? %>
                  <br>
                  Watched <%= pluralize sub.current_episode, "episode" %>.
                </p>
                <% end %>
                <div class="sub-buttons">
                  <%= link_to "Episode list", sub.show, class: "btn btn-info btn-block btn-sm mb-1" %>
                  <% if sub.cancel? %>
                    <%= form_with(model: sub) do |form| %>
                      <%= form.hidden_field :cancel, value: false %>
                      <%= form.submit "Renew subscription", class: "btn btn-outline-dark btn-block btn-sm" %>
                    <% end %>
                  <% else %>
                    <%= form_with(model: sub) do |form| %>
                      <%= form.hidden_field :cancel, value: true %>
                      <%= form.submit "Cancel subscription", class: "btn btn-outline-danger btn-block btn-sm" %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-center mt-3">
    <div class="col-3">
      <%= link_to "Find new shows!", browse_path, class: "btn btn-primary btn-lg btn-block" %>
    </div>
  </div>
</div>