config/routes.rb
Rails.application.routes.draw do
  resources :watch_histories,   only: [:index, :update]
  resources :favorites,         only: [:create, :destroy]
  resources :people,            only: [:edit, :update]
  resources :video_comments,    only: [:create, :update, :destroy]
  resources :profile_comments,  only: [:create, :update, :destroy]
  resources :movie_ratings,     only: [:create, :update, :destroy]
  resources :movie_actors,      only: [:create, :update, :destroy]
  resources :movie_genres,      only: [:create, :update, :destroy]
  resources :movies,            except: [:index]
  resources :episodes,          except: [:index, :show]
  resources :videos,            only: [:show]
  resources :show_actors,       only: [:create, :update, :destroy]
  resources :show_ratings,      only: [:create, :update, :destroy]
  resources :show_genres,       only: [:create, :update, :destroy]
  resources :shows,             except: [:index]
  resources :subscriptions,     only: [:create, :update]
  resources :customers,         except: [:index, :edit, :update]
  resources :producers,         except: [:index, :edit, :update]
  resources :friend_requests,   only: [:create, :update, :destroy]
  resources :account_activations, only: [:edit]
  root    'static_pages#home'
  get     '/about',   to: 'static_pages#about'
  get     '/contact', to: 'static_pages#contact'
  get     '/browse',  to: 'static_pages#browse'
  get     '/signup',  to: 'customers#new'
  get     '/psignup', to: 'producers#new'
  get     '/search',  to: 'static_pages#search', :as => 'search_page'
  get     '/myshows', to: 'static_pages#shows',  :as => 'my_shows'
  get     '/pro_shows', to: 'static_pages#_pro_shows'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  get     '/friends', to: 'static_pages#friends'
  delete  '/friends/:id', to: 'friends#destroy'
  get     '/my_rentals',  to: 'static_pages#my_rentals'
  post    '/movies/:id/rent', to: 'rentals#create'
  get     '/invoice', to: 'static_pages#invoice'
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  # Authorization
  before_action :logged_in_any, only: [:show]
  before_action :logged_in_producer, only: [:create, :edit, :update, :destroy]
  before_action :correct_producer, only: [:edit, :update, :destroy]

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
    @movie.video = Video.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Verify movie belongs to current producer
    def correct_producer
      redirect_to root_url unless @movie.valid_producer? current_person.user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:producer_id, :promo_image, :video_attributes => [:title, :description, :clip, :thumbnail])    
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form.fields_for :video, movie.video do |video_fields| %>
    <div class="form-group">
      <%= video_fields.label :title, style: 'color: black;' %>
      <%= video_fields.text_field :title, id: :video_title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= video_fields.label :description, style: 'color: black;' %>
      <%= video_fields.text_area :description, id: :video_description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :promo_image, style: 'color: black;' %>
      <%= form.file_field :promo_image, id: :movie_promo_image,
        accept: "image/png,image/gif,image/jpeg", direct_upload: true,
        class: "direct-upload" %>
        <%= form.hidden_field :producer_id, value: current_person.user.id %>
    </div>
    <hr>
    <div class="form-group">
      <%= video_fields.label :clip, style: 'color: black;' %>
      <%= video_fields.file_field :clip, id: :video_clip, direct_upload: true,
      class: "direct-upload", accept: "video/mp4" %>
    </div>
    <div class="form-group">
      <%= video_fields.label :thumbnail, style: 'color: black;' %>
      <%= video_fields.file_field :thumbnail, id: :video_thumbnail,
        accept: "image/png,image/gif,image/jpeg", direct_upload: true,
        class: "direct-upload" %>
    </div>
  <% end %>
  <div class="actions">
    <%= form.submit class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/movies/_movie_actor_form.erb
<% if logged_in? && current_person.producer? %>
  <div class="panel panel-default">
    <%= form_with(model: MovieActor.new, local: true, class: "panel-body") do |form| %>
    
      <%= form.hidden_field :movie_id, :value => @movie.id %>
    
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_area :name, id: :movie_actor_name, rows: "1", class: "form-control" %>
      </div>
    
      <div class="actions">
        <%= form.submit "Add actor", class: "btn btn-primary"%>
      </div>
    <% end %>
  </div>
<% end %>

app/views/movies/_movie_genre_form.html.erb
<% if logged_in? && current_person.producer? %>
  <div class="panel panel-default">
    <%= form_with(model: MovieGenre.new, local: true, class: "panel-body") do |form| %>
    
      <%= form.hidden_field :movie_id, :value => @movie.id %>
    
      <div class="form-group">
        <%= form.label :genre %>
        <%= form.select :genre, ShowGenre.genres.keys.map { |w| [w.humanize, w] }, {include_blank: ''}, class: "custom-select" %>
      </div>
    
      <div class="actions">
        <%= form.submit "Add genre", class: "btn btn-primary"%>
      </div>
    <% end %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<% provide(:title, "Edit Movie") %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-5">
      <div class="card card-default">
        <h1 id="card-text" class="card-header">Edit Movie</h1>
        <div class="card-body">
          <%= render 'form', movie: @movie %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/movies/new.html.erb
<% provide(:title, "Create New Movie") %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-5">
      <div class="card card-default">
        <h1 id="card-text" class="card-header">Create New Movie</h1>
        <div class="card-body">
          <%= render 'form', movie: @movie %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/movies/show.html.erb
<% provide(:title, @movie.title) %>
<div class="container">
  <%= render "flash_notice" %>
  <div class="row">
    <div class="col-4">
      <% if @movie.promo_image.attached? %>
        <%= image_tag(url_for(@movie.promo_image), alt: "Promo image", class: "promo-art") %>
      <% else %>
        <%= image_tag("nullPhoto.png", alt: "Promo image", class: "promo-art") %>
      <% end %>
      <hr>
      <div class="card card-default">
        <div class="card-body">
          <h4 class="text-body text-center">About</h4>
          <hr>
          <p>
            <b>Genre</b>
            <% @movie.movie_genres.each do |g| %>
              <span class="badge badge-light">
                <%= g.genre.titleize %>
                <%= link_to fa_icon("times"), g, method: :delete, class: "text-danger" if current_person.producer? %>
              </span>
            <% end %>
          </p>
          <p>
            <b>Actors</b>
            <% @movie.movie_actors.each do |a| %>
              <span class="badge badge-light">
                <%= a.name %>
                <%= link_to fa_icon("times"), a, method: :delete, class: "text-danger" if current_person.producer? %>
              </span>
            <% end %>
          </p>
          <% if current_person.producer? %>
            <div class="bg-warning p-2 mx-4">
              <h5 class="text-body text-center"><small>Edit tags</small></h5>
              <%= form_with(model: MovieGenre.new, local: true) do |form| %>
                <%= form.hidden_field :movie_id, :value => @movie.id %>
                <%= form.select :genre, MovieGenre.genres.keys.map { |w| [w.titleize, w] }, {include_blank: 'Genre'}, class: "custom-select custom-select-sm mb-2 mr-2" %>
                <%= form.submit "Add genre", class: "btn btn-primary btn-sm btn-block mb-2"%>
              <% end %>
              <%= form_with(model: MovieActor.new, local: true) do |form| %>
                <%= form.hidden_field :movie_id, :value => @movie.id %>
                <%= form.text_field :name, id: :movie_actor_name, placeholder: "Actor", class: "form-control form-control-sm mb-2 mr-2" %>
                <%= form.submit "Add actor", class: "btn btn-primary btn-sm btn-block mb-2"%>
              <% end %>
            </div>
          <% end %>
          <hr>
          <p><b>Produced by</b> <%= link_to @movie.producer.company_name, @movie.producer %></p>
        </div>
      </div>
    </div>
    <div class="col-8">
      <%= content_tag :h1, @movie.title %>
      <hr>
      <!-- button for rent, watch edit and delete-->
      <div class="btn-group mb-3">
        <% if current_person.producer? %>
          <%= link_to fa_icon('edit', text: 'Edit movie'), edit_movie_path, class: 'btn btn-secondary' %>
          <%= link_to fa_icon('trash', text: 'Delete movie'), @movie, class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure? This cannot be undone.'} %>
        <% elsif @movie.rentals.find_by customer: current_person.user %>
          <%= link_to fa_icon('play', text: 'Watch'), @movie.video, class: "btn btn-primary" %>
        <% else %>
          <%= form_with(scope: :rental, url: "#{url_for @movie}/rent") do |form| %>
            <%= form.hidden_field :movie_id, value: @movie.id %>
            <%= form.submit "Rent", class: "btn btn-info" %>
          <% end %>
        <% end %>
      </div>
      <div class="card card-default">
        <div class="card-body">
          <h3 class="text-body">Description</h3>
          <p><%= @movie.description %></p>
        </div>
      </div>
    </div>
  </div>
</div>