config/routes.rb
Rails.application.routes.draw do
  resources :watch_histories,   only: [:index, :update]
  resources :favorites,         only: [:create, :destroy]
  resources :people,            only: [:edit, :update]
  resources :video_comments,    only: [:create, :update, :destroy]
  resources :profile_comments,  only: [:create, :update, :destroy]
  resources :movie_ratings,     only: [:create, :update, :destroy]
  resources :movie_actors,      only: [:create, :update, :destroy]
  resources :movie_genres,      only: [:create, :update, :destroy]
  resources :movies,            except: [:index]
  resources :episodes,          except: [:index, :show]
  resources :videos,            only: [:show]
  resources :show_actors,       only: [:create, :update, :destroy]
  resources :show_ratings,      only: [:create, :update, :destroy]
  resources :show_genres,       only: [:create, :update, :destroy]
  resources :shows,             except: [:index]
  resources :subscriptions,     only: [:create, :update]
  resources :customers,         except: [:index, :edit, :update]
  resources :producers,         except: [:index, :edit, :update]
  resources :friend_requests,   only: [:create, :update, :destroy]
  resources :account_activations, only: [:edit]
  root    'static_pages#home'
  get     '/about',   to: 'static_pages#about'
  get     '/contact', to: 'static_pages#contact'
  get     '/browse',  to: 'static_pages#browse'
  get     '/signup',  to: 'customers#new'
  get     '/psignup', to: 'producers#new'
  get     '/search',  to: 'static_pages#search', :as => 'search_page'
  get     '/myshows', to: 'static_pages#shows',  :as => 'my_shows'
  get     '/pro_shows', to: 'static_pages#_pro_shows'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  get     '/friends', to: 'static_pages#friends'
  delete  '/friends/:id', to: 'friends#destroy'
  get     '/my_rentals',  to: 'static_pages#my_rentals'
  post    '/movies/:id/rent', to: 'rentals#create'
  get     '/invoice', to: 'static_pages#invoice'
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :content, polymorphic: true, touch: true
  has_many :video_comments, dependent: :destroy
  has_many :watch_histories, dependent: :destroy
  has_one_attached :clip
  has_one_attached :thumbnail

  validates :title, presence: true
  validates :description, presence: true
  
  # Returns true if video content is an episode
  def episode?
    content_type == "Episode"
  end

  # Returns true if video content is a movie
  def movie?
    content_type == "Movie"
  end
  
  # Return list of genres for content
  def get_content_genres
    if episode?
      return content.show.show_genres
    else
      return content.movie_genres
    end
  end
  
  # Return either show or movie that video belongs to
  def content_parent
    if episode?
      return content.show
    else
      return content
    end
  end
  
  # Returns the next video in a playlist
  def next_video
    if episode?
      episode = content.next_ep
      unless episode.nil?
        return episode.video
      end
    end
  end
  
  # Returns the next episode or the show if not found
  def next_video_or_show
    ep = next_video
    if ep.nil?
      return content.show
    else
      return ep
    end
  end
  
  # Returns the previous video in a playlist
  def prev_video
    if episode?
      episode = content.prev_ep
      unless episode.nil?
        episode.video
      end
    end
  end
  
  def content_parent
    if episode?
      return content.show
    else
      return content
    end
  end
  
  # Returns true if producer has edit permission
  def valid_producer?(producer)
    content.valid_producer?(producer)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  #Authorization
  before_action :logged_in_any, only: [:show]
  before_action :check_permission, only: [:show]
  before_action :logged_in_producer, only: [:create, :edit, :update, :destroy]
  before_action :correct_producer, only: [:edit, :update, :destroy]

  # GET /videos/1
  # GET /videos/1.json
  def show
    if current_person.customer?
      # Create or update watch history for customer
      @watch_history = WatchHistory.find_or_create_by video: @video, customer: current_person.user
      @watch_history.touch
      
      # Update subscription if needed
      if @video.episode?
        sub = current_person.user.subscriptions.find_by(show: @video.content.show)
        if sub.current_episode < @video.content.absolute_episode
          sub.current_episode = @video.content.absolute_episode
          sub.save
        end
      end
      
      # Set previous watch history as completed
      prev = @video.prev_video
      if !prev.nil?
        last_watched = WatchHistory.find_or_create_by video: prev, customer: current_person.user
        last_watched.completed = true
        last_watched.save
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end
    
    # Check if user has permission to view video
    def check_permission
      if current_person.producer?
        # Check if video is owned by producer
        correct_producer
      else
        # Check if customer has a valid subscription or rental
        @customer = current_person.user
        if @video.episode?
          unless @customer.has_subscription?(@video.content_parent)
            flash[:danger] = "Must subscribe first to view content"
            redirect_to @video.content_parent
          end
        else
          unless @customer.rentals.find_by(movie_id: @video.content_parent.id)
            flash[:danger] = "Must rent first to view content"
            redirect_to @video.content_parent
          end
        end
      end
    end
    
    # Check current user has permision to edit
    def correct_producer
      redirect_to root_url unless @video.valid_producer? current_person.user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :description, :clip, :thumbnail, :content_id, :content_type)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_comment_form.html.erb
<% if logged_in? && current_person.customer? %>
  <div class="panel panel-default">
    <%= form_with(model: VideoComment.new, local: true, class: "panel-body") do |form| %>
    
      <%= form.hidden_field :video_id, :value => @video.id %>
      <%= form.hidden_field :customer_id, :value => current_person.user.id %>
    
      <div class="form-group">
        <%= form.label :comment, "Your comment:" %>
        <%= form.text_area :comment, id: :video_comment_comment, rows: "3", class: "form-control" %>
      </div>
    
      <div class="actions">
        <%= form.submit "Post", class: "btn btn-primary"%>
      </div>
    <% end %>
  </div>
<% end %>

app/views/videos/show.html.erb
<% provide(:title, "Watching " + @video.title) %>
<div class="container">
  <%= render "flash_notice" %>
  <div class="row video-main mb-4">
    <div class="col">
      <%= content_tag :div, id: "video_p", class: "video-player", data: ({progress: @watch_history.progress, url: url_for(@watch_history)} unless current_person.producer?) do %>
        <video id="main-video-player" class="video-js vjs-default-skin vjs-16-9"
            controls autoplay preload="auto" width="640" height="264" 
            <%= if @video.thumbnail.attached? then "poster=\"#{ url_for @video.thumbnail }\"" end %>
            data-setup= '{}'>
          <source src="<%= url_for(@video.clip) %>" type="video/mp4">
          <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
        </video>
      <% end %>
    </div>
  </div>
  <div class="row video-description">
    <div class="col-9">
      <div class="card card-default mb-3">
        <div class="card-body">
          <div class="video-title">
            <h3 class="text-body">
              <%= @video.title %>
              <%= if @video.episode? then content_tag :small, @video.content.season_episode end %>
            <div class="review-buttons pull-right">
              <% @favorite = @video.content.favorites.find_by(customer_id: current_person.user.id) %>
              <% if @favorite.nil? %>
                <%= button_to "Favorite", favorites_path, params: { favorite: { content_id: @video.content_id, content_type: @video.content_type } }, class: "btn btn-primary btn-sm" %>
              <% else %>
                <%= button_to "Unfavorite", favorite_path(@favorite),  method: :delete, class: "btn btn-warning btn-sm" %>
              <% end %>
            </div>
            </h3>
          </div>
          <p><%= @video.description %></p>
        </div>
      </div>
      <div class="card card-default">
        <div class="card-body">
          <h4 class="text-body">Comments</h4>
          <% if @video.video_comments.any? %>
            <% @video.video_comments.each do |comment| %>
              <%= render comment %>
            <% end %>
          <% else %>
            <small>No comments.</small>
          <% end %>
          <div id="comment-form">
            <%= render 'comment_form' %>
          </div>
        </div>
      </div>
    </div>
    <% if @video.episode? %>
      <div class="col-3 video-playlist">
        <div class="card card-default">
          <h5 class="card-header"><%= link_to @video.content.show.name, @video.content.show %></h5>
          <div class="card-body">
            <div class="btn-group btn-block" role="group">
              <%= link_to fa_icon("chevron-left"), @video.prev_video, class: "btn btn-outline-secondary text-body", id: "button_prev" %>
              <%= link_to fa_icon("chevron-right"), url_for([@video.next_video_or_show, update: (@watch_history.id unless @watch_history.nil?)]), class: "btn btn-outline-secondary text-body", id: "button_next" %>
            </div>
            <% @video.content.show.episodes.order(:absolute_episode).each do |episode| %>
              <%= link_to episode.video do %>
                <%= content_tag :div, class: "media", style: (if episode.id == @video.content_id then "background-color: #ddd" end) do %>
                  <div class="media-body">
                    <h4 class="media-heading text-body"><%= episode.video.title %></h4>
                    <small><%= episode.season_episode %></small>
                    <p><%= episode.video.description %></p>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>
  </div>
</div>
<% if @video.episode? and !@video.next_video.nil?%>
<div class="modal fade" id="autoplayModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-body" id="autoplayModalLabel">Playing next video...</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Great video! Give us a rating or wait a bit for the next one!</p>
        <div class="text-center" id="autoplayModalLoading">
          <div class="spinner-border" role="status">
            <span class="sr-only">Waiting...</span>
          </div>
          <h3 class="text-body" id="autoplayModalTimer">10</h3>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Stop</button>
        <%= link_to "Play now", @video.next_video, type: "button", class: "btn btn-primary", "data-dismiss": "modal", id: "auto-next" %>
      </div>
    </div>
  </div>
</div>
<% end %>