config/routes.rb
Rails.application.routes.draw do
  resources :watch_histories,   only: [:index, :update]
  resources :favorites,         only: [:create, :destroy]
  resources :people,            only: [:edit, :update]
  resources :video_comments,    only: [:create, :update, :destroy]
  resources :profile_comments,  only: [:create, :update, :destroy]
  resources :movie_ratings,     only: [:create, :update, :destroy]
  resources :movie_actors,      only: [:create, :update, :destroy]
  resources :movie_genres,      only: [:create, :update, :destroy]
  resources :movies,            except: [:index]
  resources :episodes,          except: [:index, :show]
  resources :videos,            only: [:show]
  resources :show_actors,       only: [:create, :update, :destroy]
  resources :show_ratings,      only: [:create, :update, :destroy]
  resources :show_genres,       only: [:create, :update, :destroy]
  resources :shows,             except: [:index]
  resources :subscriptions,     only: [:create, :update]
  resources :customers,         except: [:index, :edit, :update]
  resources :producers,         except: [:index, :edit, :update]
  resources :friend_requests,   only: [:create, :update, :destroy]
  resources :account_activations, only: [:edit]
  root    'static_pages#home'
  get     '/about',   to: 'static_pages#about'
  get     '/contact', to: 'static_pages#contact'
  get     '/browse',  to: 'static_pages#browse'
  get     '/signup',  to: 'customers#new'
  get     '/psignup', to: 'producers#new'
  get     '/search',  to: 'static_pages#search', :as => 'search_page'
  get     '/myshows', to: 'static_pages#shows',  :as => 'my_shows'
  get     '/pro_shows', to: 'static_pages#_pro_shows'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  get     '/friends', to: 'static_pages#friends'
  delete  '/friends/:id', to: 'friends#destroy'
  get     '/my_rentals',  to: 'static_pages#my_rentals'
  post    '/movies/:id/rent', to: 'rentals#create'
  get     '/invoice', to: 'static_pages#invoice'
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :producer
  has_many :show_genres
  has_many :show_actors
  has_many :show_ratings
  has_many :episodes
  has_many :subscriptions
  validates :name, presence: true
  validates :description, presence: true
  has_one_attached :promo_image
  ratyrate_rateable 'rating'
  
  # Returns true if producer has edit permission
  def valid_producer?(producer)
    producer == self.producer
  end
  
  # Polymorphism
  def title
    name
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy]
  # Authorization
  before_action :logged_in_any, only: [:show]
  before_action :logged_in_producer, only: [:create, :edit, :update, :destroy]
  before_action :correct_producer, only: [:edit, :update, :destroy]

  # GET /shows/1
  # GET /shows/1.json
  def show
    if !params[:update].nil? and current_person.customer?
      # Update subscription for customer
      sub = current_person.user.subscriptions.find_by(show: @show)
      sub.current_episode = @show.episodes.size
      sub.save
      # Set last video as completed
      history = WatchHistory.find params[:update]
      if !history.nil? and history.customer == current_person.user
        history.completed = true
        history.save
      end
    end
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to pro_shows_path, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end
    
    # Check current user has permision to edit
    def correct_producer
      redirect_to root_url unless @show.valid_producer? current_person.user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def show_params
      params.require(:show).permit(:name, :producer_id, :description, :promo_image)
    end
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/_form.html.erb
<%= form_with(model: show, local: true) do |form| %>
  <% if show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form.fields_for :show do |show_fields| %>
    <div class="panel panel-default">
      <div class="panel-heading"><h3>Show information:</h3></div>
      <div class="panel-body">
        <div class="form-group">
          <%= form.label :promo_image, style: 'color: black;' %>
          <%= form.file_field :promo_image, id: :show_promo_image,
            accept: "image/png,image/gif,image/jpeg", direct_upload: true,
            class: "direct-upload" %>
        </div>
        <div class="form-group">
          <%= form.label :name, style: 'color: black;' %>
          <%= form.text_field :name, id: :show_name, class: "form-control" %>
          <%= form.hidden_field :producer_id, value: current_person.user.id %>
        </div>
        
        <div class="form-group">
          <%= form.label :description, style: 'color: black;' %>
          <%= form.text_field :description, id: :show_description, class: "form-control" %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shows/_show_actor_form.html.erb
<% if logged_in? && current_person.producer? %>
  <div class="panel panel-default">
    <%= form_with(model: ShowActor.new, local: true, class: "panel-body") do |form| %>
    
      <%= form.hidden_field :show_id, :value => @show.id %>
    
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_area :name, id: :show_actor_name, rows: "1", class: "form-control" %>
      </div>
    
      <div class="actions">
        <%= form.submit "Add actor", class: "btn btn-primary"%>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shows/_show_genre_form.html.erb
<% if logged_in? && current_person.producer? %>
  <div class="panel panel-default">
    <%= form_with(model: ShowGenre.new, local: true, class: "panel-body") do |form| %>
    
      <%= form.hidden_field :show_id, :value => @show.id %>
    
      <div class="form-group">
        <%= form.label :genre %>
        <%= form.select :genre, ShowGenre.genres.keys.map { |w| [w.humanize, w] }, {include_blank: ''}, class: "custom-select" %>
      </div>
    
      <div class="actions">
        <%= form.submit "Add genre", class: "btn btn-primary"%>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shows/edit.html.erb
<% provide(:title, "Edit Show") %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-5">
      <div class="card card-default">
        <h1 id="card-text" class="card-header">Edit Show</h1>
        <div class="card-body">
          <%= render 'form', show: @show %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Back', shows_path %>

app/views/shows/new.html.erb
<% provide(:title, "Create New Show") %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-5">
      <div class="card card-default">
        <h1 id="card-text" class="card-header">Create Show</h1>
        <div class="card-body">
          <%= render 'form', show: @show %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shows/show.html.erb
<% provide(:title, @show.name) %>
<div class="container">
  <%= render "flash_notice" %>
  <div class="row">
    <div class="col-4">
      <% if @show.promo_image.attached? %>
        <%= image_tag(url_for(@show.promo_image), alt: "Promo image", class: "promo-art") %>
      <% else %>
        <%= image_tag("nullPhoto.png", alt: "Promo image", class: "promo-art") %>
      <% end %>
      <hr>
      <div class="card card-default">
        <div class="card-body">
          <h4 class="text-body text-center">About</h4>
          <hr>
          <p>
            <b>Genre</b>
            <% @show.show_genres.each do |g| %>
              <span class="badge badge-light">
                <%= g.genre.titleize %>
                <%= link_to fa_icon("times"), g, method: :delete, class: "text-danger" if current_person.producer? %>
              </span>
            <% end %>
          </p>
          <p>
            <b>Actors</b>
            <% @show.show_actors.each do |a| %>
              <span class="badge badge-light">
                <%= a.name %>
                <%= link_to fa_icon("times"), a, method: :delete, class: "text-danger" if current_person.producer? %>
              </span>
            <% end %>
          </p>
          <% if current_person.producer? %>
            <div class="bg-warning p-2 mx-4">
              <h5 class="text-body text-center"><small>Edit tags</small></h5>
              <%= form_with(model: ShowGenre.new, local: true) do |form| %>
                <%= form.hidden_field :show_id, :value => @show.id %>
                <%= form.select :genre, ShowGenre.genres.keys.map { |w| [w.titleize, w] }, {include_blank: 'Genre'}, class: "custom-select custom-select-sm mb-2 mr-2" %>
                <%= form.submit "Add genre", class: "btn btn-primary btn-sm btn-block mb-2"%>
              <% end %>
              <%= form_with(model: ShowActor.new, local: true) do |form| %>
                <%= form.hidden_field :show_id, :value => @show.id %>
                <%= form.text_field :name, id: :show_actor_name, placeholder: "Actor", class: "form-control form-control-sm mb-2 mr-2" %>
                <%= form.submit "Add actor", class: "btn btn-primary btn-sm btn-block mb-2"%>
              <% end %>
            </div>
          <% end %>
          <hr>
          <p><b>Description</b> <%= @show.description %></p>
          <p><b>Produced by</b> <%= link_to @show.producer.company_name, @show.producer %></p>
        </div>
      </div>
    </div>
    <div class="col-8">
      <%= content_tag :h1, @show.name %>
      <hr>
      <div class="btn-group mb-3">
          <% if current_person.producer? %>
            <%= link_to fa_icon('plus', text: 'Add episode'), new_episode_path(show_id: @show.id), class: "btn btn-secondary btn-large" %>
            <%= link_to fa_icon('edit', text: 'Edit show'), edit_show_path, class: "btn btn-secondary btn-large" %>
            <%= link_to fa_icon('trash', text: 'Delete show'), @show, class: "btn btn-danger btn-large", method: :delete, data: { confirm: 'Are you sure? This cannot be undone.' } %>
          <% else %>
            <% if !current_person.user.has_subscription?(@show) %>
              <button type="button" class="btn btn-info btn-large" data-toggle="modal" data-target="#exampleModal">
                <%= fa_icon "plus", text: "Subscribe" %>
              </button>
              <!-- Modal -->
              <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title text-body" id="exampleModalLabel">Subscribe to <%= @show.name %></h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <% if current_person.user.open_slots? %>
                      <div class="modal-body text-body">
                        You have <span class="text-warning"><%= current_person.user.open_slots %></span> available subscription slots remaining.
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <%= button_to "Subscribe", subscriptions_path,
                          params: { subscription: { customer_id:
                          current_person.user.id, show_id: @show.id} },
                          class:"btn btn-primary" %>
                      </div>
                    <% else %>
                      <div class="modal-body text-body">
                        You do not have any available subscription slots. You can 
                        purchase an additional slot for $2. Select "Purchase" to 
                        add a new slot and subscribe to this show.
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <%= button_to "Purchase", subscriptions_path,
                          params: { subscription: { customer_id:
                          current_person.user.id, show_id: @show.id}, purchase: true },
                          class:"btn btn-warning" %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
              
              <%= link_to fa_icon("play", text: "Watch All"), @show.episodes.order(:absolute_episode).first.video, class: "btn btn-lg btn-primary disabled" %>
            <% else %>
              <%= link_to fa_icon("play", text: "Watch all"), @show.episodes.order(:absolute_episode).first.video, class: "btn btn-lg btn-primary" %>
            <% end %>
          <% end %>
      </div>
      <h3>Episodes</h3>
      <% @show.episodes.order(:absolute_episode).includes(video: {thumbnail_attachment: :blob}).each do |episode| %>
        <div class="row">
          <div class="col mb-2">
            <div class="card card-default ep-show">
              <div class="card-body">
                <% if episode.video.thumbnail.attached? %>
                  <%= image_tag(url_for(episode.video.thumbnail), size: "100x100", alt: "Thumbnail") %>
                <% else %>
                  <%= image_tag("nullPhoto.png", size: "100x100", alt: "Thumbnail", class: "ep-show") %>
                <% end %>
                <h5 class="text-body"><%= episode.video.title %> <small class="text-secondary"><%= episode.season_episode %></small></h5>
                <p><%= episode.video.description %></p>
                <div id="ep-button-block">
                  <% if current_person.customer? %>
                    <%= link_to "Play", episode.video, class: "btn btn-secondary btn-sm" %>
                  <% else %>
                    <%= link_to "Edit", edit_episode_path(episode), class: "btn btn-secondary btn-sm" %>
                    <%= link_to "Delete", episode, class: "btn btn-danger btn-sm" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
  